theme = "slick"
icons = "none"

[[block]]
block = "temperature"
collapsed = false
interval = 10
format = "{max}° max, {average}° avg"

[[block]]
block = "disk_space"
path = "/"
alias = "/"
info_type = "available"
unit = "GB"
interval = 20


[[block]]
block = "memory"
display_type = "memory"
format_mem = "{Mup}%"
format_swap = "{SUp}%"

[[block]]
block = "cpu"
interval = 1
frequency = true

[[block]]
block = "load"
interval = 1
format = "{1m}"

[[block]]
block = "net"
device = "enp3s0"
ssid = true
ip = false
speed_up = false
graph_down = true
interval = 5

[[block]]
block = "sound"
step_width = 5

[[block]]
block = "time"
interval = 60
format = "%m/%d %a %R"
