theme = "slick"
icons = "awesome"


[[block]]
block = "pacman"
interval = 14400

[[block]]
block = "temperature"
collapsed = false
interval = 10
format = "{max}° max, {average}° avg"


[[block]]
block = "memory"
display_type = "memory"
format_mem = "{Mup}%"
format_swap = "{SUp}%"

[[block]]
block = "cpu"
interval = 1
frequency = true

[[block]]
block = "load"
interval = 1
format = "{1m}"

[[block]]
block = "net"
device = "enp3s0"
ssid = true
ip = false
speed_up = false
graph_up = true
interval = 5

[[block]]
block = "sound"
step_width = 5

[[block]]
block = "time"
interval = 60
format = "%m/%d %a %R"
